# Generated by Django 3.2.9 on 2021-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Position', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
