# Generated by Django 3.2.9 on 2021-12-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Age',
            field=models.CharField(max_length=20),
        ),
    ]
